name: Close stale PRs

on:
  schedule:

    - cron: '0 0 * * 1'

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2


      - name: Set up Python and install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install PyGithub==1.55


      - name: Close stale PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python - <<EOF
          import os
          from datetime import datetime, timedelta
          from github import Github
          
          # Get the current time and the time 3 weeks ago
          now = datetime.now()
          days_ago = now - timedelta(days=25)
          
          # Authenticate with the GitHub API
          g = Github(os.getenv('GITHUB_TOKEN'))
          repo = g.get_repo('harness/harness-core')
          
          # Get all open PRs for the repository
          prs = repo.get_pulls(state='open')
          
          # Loop through each PR and close it if it's stale
          for pr in prs:
              last_updated = pr.updated_at
              if last_updated < days_ago:
                  pr.create_issue_comment("This pull request has been automatically closed because it hasn't been updated in 25 days.")
                  pr.edit(state='closed')
          EOF
